name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Node dependencies
      working-directory: WebSocket
      run: npm install

    #  Compile C++ with Windows compiler
    - name: Compile C++
      working-directory: controller-visualiser
      run: |
         g++ src/main.cpp ixwebsocket/*.cpp -o mouse.exe -I . -lws2_32

    - name: Run tests
      working-directory: WebSocket
      run: npm test